#!/usr/bin/env bash
set -eux

# parse arguments

mode='normal'


key="--dummy"
while [[ $key =~ ^--* ]]
do
  key="$1"
  case $key in
    --*)
    mode="${key#--}"
    shift # past argument
    ;;
    -*)
    key="${key#-}"
    value="$2"
    declare "$key=$value"
    shift # key
    shift # value
    ;;
  esac
done

command="$1"
args="${@:2}"

# find compose files in these dirs
services=(
  client 
  server
)

# build the docker-compose command
script="docker-compose -p fluxcell "

for service in "${services[@]}"
do
  script+="-f ./$service/docker-compose.yml "
  if [[ $mode == 'dev' ]];
    then
      script+="-f ./$service/docker-compose-dev.yml "
  fi
done

script+="$command $args"

# run the docker-compose command
eval "$script"
